default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  port: 5432
  host: localhost

development:
  <<: *default
  database: sha_project

test:
  <<: *default
  database: sha_project_test
